# Based on
# https://github.com/arcelioeperez/NotebooksC/blob/main/environment.yml
# https://github.com/betatim/vscode-binder

name: xeus-cling
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xeus-cling
  - xtensor
  - xtensor-blas
  - notebook
  - cmake
  - cxx-compiler
  - cpp-argparse
  - python
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - jupyterlab
  - jupyterlab-lsp
  - jupyter-vscode-proxy
  - python-lsp-server
  # - ipywidgets
  # - jupyter_contrib_nbextensions
  # - pandas
  # - pulp
  # - bokeh
  # - plotly
  # - vpython
  # - jupyterlab-vpython
  # - pip
  # - pip:
  #   - nbgrader
