# Based on
# https://github.com/arcelioeperez/NotebooksC/blob/main/environment.yml
# https://github.com/betatim/vscode-binder

name: ProgCPP-dev
channels:
  - conda-forge
dependencies:
  - notebook
  - cmake
  - clang
  - gcc
  #- cxx-compiler
  #- cpp-argparse
  #- graphviz
  #- libblas
  #- liblapack
  #- libuuid
  #- openmpi
  #- ninja
  #- pkg-config
  - python >=3.9
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - jupyterlab
  - jupyterlab-lsp
  # - jupyter-vscode-proxy
  - python-lsp-server
  # - code-server
  # - ipywidgets
  - jupyter_contrib_nbextensions
  # - pandas
  # - pulp
  # - bokeh
  # - plotly
  # - vpython
  # - jupyterlab-vpython
  - pip
  # - pip:
  #   - nbgrader
