#!/bin/bash

# From https://github.com/binder-examples/latex/blob/master/postBuild

# # run matplotlib once to generate the font cache
# python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

# test -e test.png && rm test.png

code-server --install-extension ms-python.python
code-server --install-extension ms-vscode.cpptools

# Install the VS code proxy
pip install -e.
