#!/bin/bash

# From https://github.com/binder-examples/latex/blob/master/postBuild

# # run matplotlib once to generate the font cache
# python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

# test -e test.png && rm test.png

#gfortran
#curl -fsSL https://code-server.dev/install.sh | sh
#code-server --install-extension ms-python.python

# Install the VS code proxy
#pip install -e.
